# Generated by Django 5.0.7 on 2024-08-25 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='book/main_image', verbose_name='تصویر')),
                ('published', models.BooleanField(default=False, verbose_name='انتشار')),
            ],
            options={
                'verbose_name': 'کتاب قوانبن',
                'verbose_name_plural': 'کتاب',
            },
        ),
        migrations.CreateModel(
            name='ContactUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی')),
                ('phone', models.PositiveIntegerField(verbose_name='شماره موبایل')),
                ('done', models.BooleanField(default=False, verbose_name='در دست انجام')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'ارتباط با کاربر',
                'verbose_name_plural': 'ارتباط با کاربران',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='نام برند')),
                ('image', models.ImageField(upload_to='customers/images', verbose_name='تصویر برند')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'برند مشتری',
                'verbose_name_plural': 'برند مشتریان',
            },
        ),
        migrations.CreateModel(
            name='AccountingBookLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='بدنه متن')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='home_app.accountingbook')),
            ],
            options={
                'verbose_name': 'سطر',
                'verbose_name_plural': 'سطر ها',
            },
        ),
    ]
