# Generated by Django 5.0.7 on 2024-08-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusers',
            name='phone',
            field=models.PositiveBigIntegerField(verbose_name='شماره موبایل'),
        ),
    ]
