# Generated by Django 5.0.7 on 2024-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExelFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('status', models.BooleanField(default=False, help_text='اگر تیک را بزنید کاربران میتوانند این فایل را مشاهده یا دانلود کنند', verbose_name='وضعیت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/exel-images', verbose_name='تصویر')),
                ('file', models.FileField(upload_to='exel-files', verbose_name='فایل اکسل')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
            ],
            options={
                'verbose_name': 'فایل اکسل',
                'verbose_name_plural': 'فایل های اکسل',
            },
        ),
    ]
