# Generated by Django 5.0.7 on 2024-08-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exelfiles',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=200, unique=True),
        ),
    ]
