# Generated by Django 5.0.7 on 2024-08-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleinline',
            options={'verbose_name': 'سطر', 'verbose_name_plural': 'سطرها'},
        ),
        migrations.AlterField(
            model_name='articleinline',
            name='body',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='articleinline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/article/inline', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='articleinline',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان'),
        ),
    ]
