# Generated by Django 5.0.7 on 2024-08-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_alter_articleinline_options_alter_articleinline_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_app.category', verbose_name='دسته بندی'),
        ),
    ]
