# Generated by Django 5.0.7 on 2024-08-15 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128, verbose_name='نام و نام خانوادگی')),
                ('phone', models.PositiveIntegerField(max_length=11, verbose_name='شماره موبایل')),
                ('message', models.TextField(verbose_name='پیام')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='article_app.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'نطر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
