# Generated by Django 5.0.7 on 2024-08-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0004_articlemessage_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinline',
            name='body',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='متن'),
        ),
    ]
