# Generated by Django 5.0.7 on 2024-08-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0005_alter_articleinline_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemessage',
            name='phone',
            field=models.PositiveBigIntegerField(max_length=11, verbose_name='شماره موبایل'),
        ),
    ]
